Move away from enums
cisco-open/cisco-catalyst-wan-sdk pull request #725
Opened 2024-06-07 13:34 UTC by jpkrajewski

# Pull Request summary:
Change device_model to str

# Description of changes:
```python
from catalystwan.api.templates.cli_template import CLITemplate
from catalystwan.utils.device_model import DeviceModel
import requests
from catalystwan.session import create_manager_session

# Disable warnings about insecure requests (self-signed certificates, etc.)
requests.packages.urllib3.disable_warnings()

# Replace with your vManage details
VMANAGE_URL = 'https://vmanage-url'
USERNAME = 'your-username'
PASSWORD = 'your-password'
DEVICE_HOSTNAME = 'vm1'
TEMPLATE_NAME = 'template_test'

# Establish a session with vManage
with create_manager_session(url=VMANAGE_URL, username=USERNAME, password=PASSWORD) as session:
    
    # Step 1: Get the running configuration of the device
    devices = session.api.devices.get()
    device = devices.filter(hostname=DEVICE_HOSTNAME).single_or_default(default=None)
    
    if device:
        # Step 2: Create a CLI Template with the running config
        cli_template = CLITemplate(
            template_name=TEMPLATE_NAME,
            template_description="CLI Template",
            device_model=device.model,
        )
        cli_template.load_running(session, device)
        session.api.templates.create(cli_template)
        # Step 3: Attach the template to the device
        session.api.templates.attach(TEMPLATE_NAME, device)
        
        print(f"CLI Template created and attached to device {DEVICE_HOSTNAME}.")
    else:
        print(f"Device with hostname {DEVICE_HOSTNAME} not found.") 
```

Following script throws en error:

```
Traceback (most recent call last):
  File "/home/jakub/data.py", line 37, in <module>
    session.api.templates.create(cli_template)
  File "/home/jakub/work/catalystwan/catalystwan/api/template_api.py", line 431, in create
    template_id = self._create_cli_template(template)
  File "/home/jakub/work/catalystwan/catalystwan/api/template_api.py", line 448, in _create_cli_template
    payload = template.generate_payload()
  File "/home/jakub/work/catalystwan/catalystwan/api/templates/cli_template.py", line 70, in generate_payload
    "deviceType": self.device_model.value,
AttributeError: 'str' object has no attribute 'value'
```

Since device has an str instead of Enum

```python
@define
class Device(DataclassBase):
    uuid: str
    personality: Personality = field(converter=Personality)
    ...
    model: Optional[str] = field(default=None, metadata={FIELD_NAME: "device-model"})
    ...
```

# Checklist:
- [ ] Make sure to run pre-commit before committing changes
- [ ] Make sure all checks have passed
- [ ] PR description is clear and comprehensive
- [ ] Mentioned the issue that this PR solves (if applicable)
- [ ] Make sure you test the changes

2024-06-07 13:53 UTC, smialy approved these changes

2024-06-07 13:55 UTC, cicharka approved these changes

2024-06-07 14:14 UTC, cicharka requested changes
this change will not improve usage right now, we have to move to Literals instead of just accepting the string

2024-06-11 05:46 UTC, smialy approved these changes

2024-06-20 12:27 UTC, closed without merging