add support for tenant level user to make API calls for mtt aaa
cisco-open/cisco-catalyst-wan-sdk pull request #850
Opened 2024-10-31 22:45 UTC by nikhilkp93

# Pull Request summary:
add support for tenant level user to make API calls for mtt aaa.
currently only provider as a tenant user is able to make API calls

# Description of changes:
i have added 2 more classes, where we don't invoke provider level APIs.
So tenant level users can add tacacs or radius servers

# Checklist:
- [X] Make sure to run pre-commit before committing changes
- [X] Make sure all checks have passed
- [X] PR description is clear and comprehensive
- [X] Mentioned the issue that this PR solves (if applicable)
- [X] Make sure you test the changes

2024-11-01 19:26 UTC, renukavinay reviewed
tenant_id is used for logging purpose. Add tenant name using the session

2024-11-01 21:02 UTC, nikhilkp93 commented
> tenant_id is used for logging purpose. Add tenant name using the session

Is there an API to get the tenant name from tenant level, that I can use for this ?

2024-11-02 12:02 UTC, sbasan approved these changes

2024-11-05 09:13 UTC, sbasan requested changes

2024-11-05 09:13 UTC, sbasan commented on catalystwan/api/mtt_aaa_api.py
> +        logger.debug("TACACS config {self.tenant_org_name}")
Are you aware that `add_tacacs` method will make two requests to vManage each time it is invoked?
`GET /settings/configuration/organization`
`POST /dataservice/admin/tacacs`
Why we want to mix tacas API with settings API? I think this is unnecessary coupling.

2024-11-05 16:00 UTC, JimOverholt commented on catalystwan/api/mtt_aaa_api.py
> +        logger.debug("AAA config {self.tenant_org_name}")
```suggestion
        logger.debug(f"AAA config {self.tenant_org_name}")
```

2024-11-05 16:01 UTC, JimOverholt commented on catalystwan/api/mtt_aaa_api.py
> +        logger.debug("Delete AAA config on tenant {self.tenant_org_name}")
```suggestion
            raise AAAConfigNotPresent(f"No AAA config present for Tenant {self.tenant_org_name}")
        logger.debug(f"Delete AAA config on tenant {self.tenant_org_name}")
```

2024-11-05 16:32 UTC, sbasan commented on catalystwan/api/mtt_aaa_api.py
> +        logger.debug("TACACS config {self.tenant_org_name}")
These methods can be easily decorated outside SDK if specific logging is needed.

2024-11-06 16:55 UTC, renukavinay submitted a review, later dismissed

2024-11-06 18:51 UTC, sbasan submitted a review, later dismissed

2024-11-06 18:55 UTC, renukavinay submitted a review, later dismissed
mock session endpoints could have been added in unittest. 
otherwise lgtm

2024-11-06 21:47 UTC, bboot2 approved these changes

2024-11-06 21:47 UTC, merged